name:  CI Branches

on:
    push:
        branches-ignore:
            - 'master'

jobs:
    test:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node 10.x
              uses: actions/setup-node@v2
              with:
                  node-version: '10.x'

            - name: Unit Testing
              run: |
                  npm install
                  npm run test
